/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as ComunidadRouteImport } from './routes/comunidad'
import { Route as EntrenadorRouteImport } from './routes/entrenador'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as NutricionRouteImport } from './routes/nutricion'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ProgresoRouteImport } from './routes/progreso'
import { Route as RecetasRouteImport } from './routes/recetas'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ApiCoachRouteImport } from './routes/api/coach'
import { Route as SesionIndexRouteImport } from './routes/sesion.$index'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadRoute = ComunidadRouteImport.update({
  id: '/comunidad',
  path: '/comunidad',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrenadorRoute = EntrenadorRouteImport.update({
  id: '/entrenador',
  path: '/entrenador',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const NutricionRoute = NutricionRouteImport.update({
  id: '/nutricion',
  path: '/nutricion',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgresoRoute = ProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => rootRouteImport,
} as any)
const RecetasRoute = RecetasRouteImport.update({
  id: '/recetas',
  path: '/recetas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachRoute = ApiCoachRouteImport.update({
  id: '/api/coach',
  path: '/api/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const SesionIndexRoute = SesionIndexRouteImport.update({
  id: '/sesion/$index',
  path: '/sesion/$index',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/comunidad': typeof ComunidadRoute
  '/entrenador': typeof EntrenadorRoute
  '/legal': typeof LegalRoute
  '/nutricion': typeof NutricionRoute
  '/perfil': typeof PerfilRoute
  '/plan': typeof PlanRoute
  '/progreso': typeof ProgresoRoute
  '/recetas': typeof RecetasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/coach': typeof ApiCoachRoute
  '/sesion/$index': typeof SesionIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/comunidad': typeof ComunidadRoute
  '/entrenador': typeof EntrenadorRoute
  '/legal': typeof LegalRoute
  '/nutricion': typeof NutricionRoute
  '/perfil': typeof PerfilRoute
  '/plan': typeof PlanRoute
  '/progreso': typeof ProgresoRoute
  '/recetas': typeof RecetasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/coach': typeof ApiCoachRoute
  '/sesion/$index': typeof SesionIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/comunidad': typeof ComunidadRoute
  '/entrenador': typeof EntrenadorRoute
  '/legal': typeof LegalRoute
  '/nutricion': typeof NutricionRoute
  '/perfil': typeof PerfilRoute
  '/plan': typeof PlanRoute
  '/progreso': typeof ProgresoRoute
  '/recetas': typeof RecetasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/coach': typeof ApiCoachRoute
  '/sesion/$index': typeof SesionIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/comunidad'
    | '/entrenador'
    | '/legal'
    | '/nutricion'
    | '/perfil'
    | '/plan'
    | '/progreso'
    | '/recetas'
    | '/reset-password'
    | '/api/coach'
    | '/sesion/$index'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coach'
    | '/comunidad'
    | '/entrenador'
    | '/legal'
    | '/nutricion'
    | '/perfil'
    | '/plan'
    | '/progreso'
    | '/recetas'
    | '/reset-password'
    | '/api/coach'
    | '/sesion/$index'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/coach'
    | '/comunidad'
    | '/entrenador'
    | '/legal'
    | '/nutricion'
    | '/perfil'
    | '/plan'
    | '/progreso'
    | '/recetas'
    | '/reset-password'
    | '/api/coach'
    | '/sesion/$index'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachRoute: typeof CoachRoute
  ComunidadRoute: typeof ComunidadRoute
  EntrenadorRoute: typeof EntrenadorRoute
  LegalRoute: typeof LegalRoute
  NutricionRoute: typeof NutricionRoute
  PerfilRoute: typeof PerfilRoute
  PlanRoute: typeof PlanRoute
  ProgresoRoute: typeof ProgresoRoute
  RecetasRoute: typeof RecetasRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiCoachRoute: typeof ApiCoachRoute
  SesionIndexRoute: typeof SesionIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad': {
      id: '/comunidad'
      path: '/comunidad'
      fullPath: '/comunidad'
      preLoaderRoute: typeof ComunidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrenador': {
      id: '/entrenador'
      path: '/entrenador'
      fullPath: '/entrenador'
      preLoaderRoute: typeof EntrenadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutricion': {
      id: '/nutricion'
      path: '/nutricion'
      fullPath: '/nutricion'
      preLoaderRoute: typeof NutricionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progreso': {
      id: '/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof ProgresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recetas': {
      id: '/recetas'
      path: '/recetas'
      fullPath: '/recetas'
      preLoaderRoute: typeof RecetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach': {
      id: '/api/coach'
      path: '/api/coach'
      fullPath: '/api/coach'
      preLoaderRoute: typeof ApiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sesion/$index': {
      id: '/sesion/$index'
      path: '/sesion/$index'
      fullPath: '/sesion/$index'
      preLoaderRoute: typeof SesionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachRoute: CoachRoute,
  ComunidadRoute: ComunidadRoute,
  EntrenadorRoute: EntrenadorRoute,
  LegalRoute: LegalRoute,
  NutricionRoute: NutricionRoute,
  PerfilRoute: PerfilRoute,
  PlanRoute: PlanRoute,
  ProgresoRoute: ProgresoRoute,
  RecetasRoute: RecetasRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiCoachRoute: ApiCoachRoute,
  SesionIndexRoute: SesionIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
